sonarqube:
  serverUrl: http://sonarqube.eazybuilder-devops.cn
  user: admin
  password: admin
  url: http://sonarqube.eazybuilder-devops.cn/api/ce/task?id=AXvxxRD_0S3DvZAIEzr4


project:
  url: http://gitlab.eazybuilder-devops.cn/

nexus3:
  url: nexus3.eazybuilder-devops.cn

jenkins:
  maven:
    url: 127.0.0.1
  url: jenkins.eazybuilder-devops.cn
  username: admin
  password: admin


registry:
  url: registry.eazybuilder-devops.cn

gitlabApi:
  url: gitlab-api.eazybuilder-devops.cn

mysql:
  username: root
  password: root
  url: mysql.eazybuilder-devops.cn

base:
  url: ci-ingress.eazybuilder-devops.cn

ingress:
  host: hpa-web.eazybuilder-devops.cn

nacos:
  url: nacos.eazybuilder-devops.cn
