name: test
developers: 
  - 
    name: dev1
    email: xx@163.com
  - 
    name: dev2
    email: xx@163.com
scm: 
  type: svn
  url: http://localhost
  user: zhangsan
  password: password

deployInfo: 
  host: 127.0.0.1
  user: root
  password: password
   
registry: 
  schema: http
  url: 0.0.0.0:5000
  user: 
  password: 